### ISSUE TITLE
Add sealing for specific functions

### ISSUE THREAD

**Issue by TheLazyDutchman** [jmg-duarte/sealed-rs#18]
I recently read [a very nice blog about sealed traits](https://predr.ag/blog/definitive-guide-to-sealed-traits-in-rust/).
It talked about a few ways to seal not simply a trait, but specific methods that are part of the trait.
It is possible to seal a method, either for implementation, or also for use.

I am not sure if this would be a good addition to this crate, as it is quite niche, as well as somewhat different from what this crate is doing.

I think however, that it would make sense for the ecosystem that if this feature would be a thing, it would be in this crate, as it seems to me as a natural extension.

If others agree that it should be in here I'd be more than happy to make a PR for it, otherwise I'll make my own crate for it.

**Comment by jmg-duarte** [comment]
This seems to be within scope of the crate. 

I'd be happy to review a PR and help you get this merged!
