### ISSUE TITLE
`#[diagnostic::on_unimplemented]` could be used to improve error messages

### ISSUE THREAD

**Issue by MingweiSamuel** [jmg-duarte/sealed-rs#20]
https://blog.rust-lang.org/2024/05/02/Rust-1.78.0.html#diagnostic-attributes
https://doc.rust-lang.org/nightly/reference/attributes/diagnostics.html#the-diagnostic-tool-attribute-namespace

**Comment by jmg-duarte** [comment]
@MingweiSamuel I gave it a go and didn't really help. 

`Sealed` is somewhat hidden and isn't the one people should be worrying about implementing, the macro should do that for them. Maybe if you have a concrete use case for the diagnostic, I can try, but as it stands, I don't see how it helps `sealed`'s use case

**Comment by jmg-duarte** [comment]
Closing due to lack of response.
