### ISSUE TITLE
Error when referencing associated type of supertrait

### ISSUE THREAD

**Issue by MingweiSamuel** [jmg-duarte/sealed-rs#21]
Will look more into this:
```
#[sealed]
pub trait CopyIterator: std::iter::Iterator
where
    Self::Item: Copy,
{
}
```
fails

Can workaround by adding redundant `Self: Iterator` bound or by using `#[sealed(erase)]` instead

**Comment by MingweiSamuel** [comment]
Now I'm wondering... does the sealed trait need to have generics at all? Could it just always be `trait Sealed {}`?

**Comment by tyranron** [comment]
@jmg-duarte 

> could you shed a light on this?

What is unclear from the original issue? It seems that "More benefits" section of it is quite illustrative and explanatory, providing the use case why removing generics from `trait Sealed` leads to overlapping trait impls when the original trait has them.

**Comment by jmg-duarte** [comment]
> the use case why removing generics from trait Sealed leads to overlapping trait impls when the original trait has them.

I get it now, thanks!
