### ISSUE TITLE
Allow to seal blanket impls

### ISSUE THREAD

**Issue by tyranron** [jmg-duarte/sealed-rs#4]
## Synopsis

With the current implementation it's impossible to seal a trait having blanket implementations and foreign types. For example:

```rust
#[sealed]
pub trait AsSpan {
    fn as_span(&self) -> Span;
}

impl AsSpan for Span {  // foreign type, cannot place #[sealed]
    fn as_span(&self) -> Self { *self }
}

impl<T: Spanned> AsSpan for &T { // blanket impl, cannot place #[sealed]
    fn as_span(&self) -> Span { self.span() }
}
```

## Proposed solution

Place `#[sealed]` attribute on `impl` blocks rather than on types:
```rust
#[sealed]
pub trait AsSpan {
    fn as_span(&self) -> Span;
}
// expands to:
// pub trait AsSpan: private::Sealed {
//     fn as_span(&self) -> Span;
// }
// mod private {
//     pub trait Sealed {}
// }

#[sealed]
impl AsSpan for Span {
    fn as_span(&self) -> Self { *self }
}
// expands to:
// impl AsSpan for Span {  // foreign type, cannot place #[sealed]
//     fn as_span(&self) -> Self { *self }
// }
// impl private::Sealed for Span {}

#[sealed]
impl<T: Spanned> AsSpan for &T {
    fn as_span(&self) -> Span { self.span() }
}
// expands to:
// impl<T: Spanned> AsSpan for &T {
//     fn as_span(&self) -> Span { self.span() }
// }
// impl<T: Spanned> private::Sealed for &T {}
```
[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ab7873cc30c2411bc578b3ce669211bc)

## More benefits

Also, having a flat trait signature like `pub trait Sealed {}` imposes problems with coherence for more complicated traits. Consider the following example:
```rust
pub trait Set<V> {}

impl<T> Set<Option<T>> for T {}
impl<T> Set<Option<T>> for Option<T> {}
```
This [compiles perfectly well](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5c493039d955c51e2831d2f8efbc3ff6). But once we seal it, we loose the coherence:
```rust
pub trait Set<V>: private::Sealed {}
mod private {
    pub trait Sealed {}
}

impl<T> Set<Option<T>> for T {}
impl<T> private::Sealed for T {}

impl<T> Set<Option<T>> for Option<T> {}
impl<T> private::Sealed for Option<T> {}
```
[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=44e3d6a5a4665d4f4f4125adce1abfdd)

To overcome this limitation, the `private::Sealed` trait should fully follow the parametrization of the original trait:
```rust
pub trait Set<V>: private::Sealed<V> {}
mod private {
    pub trait Sealed<V> {}
}

impl<T> Set<Option<T>> for T {}
impl<T> private::Sealed<Option<T>> for T {}

impl<T> Set<Option<T>> for Option<T> {}
impl<T> private::Sealed<Option<T>> for Option<T> {}
```
[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7f13fd7c25c07f631478ed466f49391c)

And we cannot do that by putting a `#[sealed]` attribute on top of a type rather than an impl block, because we simply don't have parametrization info there.

**Comment by tyranron** [comment]
@jmg-duarte if you're not against such redesign, I'd like to contribute this via PR in few days.

**Comment by jmg-duarte** [comment]
Closing in favor of #6
