### ISSUE TITLE
Support #[sealed] on enum

### ISSUE THREAD

**Issue by mpfaff** [jmg-duarte/sealed-rs#8]
Currently, using `#[sealed]` on an enum fails with `expected struct or trait`. I don't see a reason this shouldn't work on enums too, besides not being implemented in the macro.

**Comment by jmg-duarte** [comment]
The `#[sealed]` macro has been redesigned to be used only on `impl`s and `trait`s.

The error you got has been fixed in the upcoming 0.2.1, thank you!

I've also added a test with enums, see [here](https://github.com/jmg-duarte/sealed-rs/commit/67a8c7fbd134338449b71367f254ab32fbcb55b5)
